### ISSUE TITLE
Membuat Konfigurasi Aplikasi

### ISSUE THREAD

**Issue by fauzana18** [Super-Bootcamp-2021-Fermium/16-doc-and-config#2]
## Konfigurasi aplikasi
1. buat konfigurasi service menggunakan `rc` dengan nama `tm`
    - bisa diakses dengan file `.tmrc`
1. buat konfugrasi webapp menggunakan plugin `.env` di webpack

**Comment by aliformer** [comment]
rc config and env configdone, waiting for review
